version: '3.8'
services:
    web:
        build: .
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        environment:
            DB_CONNECTION: pgsql
            DB_HOST: db
            DB_PORT: 5432
            DB_DATABASE: confgest_dev
            DB_USERNAME: postgres
            DB_PASSWORD: ${DB_PASSWORD}
    db:
        image: postgres:16
        environment:
            POSTGRES_DB: confgest_dev
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        ports:
            - "5432:5432"
        volumes:
            - pgdata:/var/lib/postgresql/data
volumes:
    pgdata:
